### ISSUE TITLE
cv2 can't read video

### ISSUE THREAD

**Issue by sy0209** [ishwarsawale/real-time-face-recognition-with-facenet#1]
I faced the issue when run detect_facese_real_time_with_incFrame.py 
The frame is false.

I run this program in Ubuntu.
can you help me to solve it? 
Is it because of openCV issue?

**Comment by ishwarsawale** [comment]
Hi, I am giving input to cv2 as the recorded video for the test at this line  
video_capture = cv2.VideoCapture('./test.mp4')
if you want to use webcam just change it to 
video_capture = cv2.VideoCapture(0)

**Comment by sy0209** [comment]
Thank You. It is work for me now. May I know where to declare HumanNames in detect_facese_real_time.py?

**Comment by kushika** [comment]
video_capture = cv2.VideoCapture(0)
video_capture.isOpened() returns false.
video_capture = cv2.VideoCapture(-1)
Now, it returns true and webcam was working in my case.
