### ISSUE TITLE
classify issue

### ISSUE THREAD

**Issue by niu-niu** [ishwarsawale/real-time-face-recognition-with-facenet#2]
It does recognize me by giving correct label. However, it also gives my label to others (if I have not put their image in the input_dir). I tried to put a empty folder named "unknown" for unknown people. But, then it labels every one "unknown". Can anyone help me?

**Comment by ishwarsawale** [comment]
It is giving your name to other people's name because not trained on their faces, to classify the person as unknown, just compare probability range in the code for giving fac eg if myPic_probability is < .92 label = unknown.

**Comment by darkeddy** [comment]
Could you give an example please?
